// const employees = [
//   {
//     employeeId: "EMP-2101",
//     fullName: "Aditi Malhotra",
//     email: "aditi.malhotra@company.com",
//     department: "Engineering",
//     designation: "Data Scientist",
//     salary: 2954628,
//     joiningDate: "2021-01-09",
//     workMode: "On-site",
//     status: "Notice Period",
//     reportingTo: "Bhavna Malhotra",
//     skills: ["Market Research", "Figma", "SQL"],
//   },
//   {
//     employeeId: "EMP-2102",
//     fullName: "Rahul Reddy",
//     email: "rahul.reddy@company.com",
//     department: "Marketing",
//     designation: "Growth Lead",
//     salary: 1006504,
//     joiningDate: "2021-10-24",
//     workMode: "Hybrid",
//     status: "Probation",
//     reportingTo: "Tanvi Mehta",
//     skills: ["Java", "Public Speaking", "Leadership"],
//   },
//   {
//     employeeId: "EMP-2103",
//     fullName: "Priya Mehta",
//     email: "priya.mehta@company.com",
//     department: "Design",
//     designation: "Graphic Designer",
//     salary: 1501450,
//     joiningDate: "2020-05-12",
//     workMode: "Remote",
//     status: "On Leave",
//     reportingTo: "Kavita Joshi",
//     skills: ["CRM", "Excel", "Java"],
//   },
//   {
//     employeeId: "EMP-2104",
//     fullName: "Amit Patel",
//     email: "amit.patel@company.com",
//     department: "Engineering",
//     designation: "DevOps Engineer",
//     salary: 3383709,
//     joiningDate: "2020-07-04",
//     workMode: "Hybrid",
//     status: "Active",
//     reportingTo: "Shweta Sharma",
//     skills: ["CRM", "Java", "Python"],
//   },
//   {
//     employeeId: "EMP-2105",
//     fullName: "Sneha Patel",
//     email: "sneha.patel@company.com",
//     department: "Sales",
//     designation: "Account Executive",
//     salary: 3278492,
//     joiningDate: "2022-11-11",
//     workMode: "On-site",
//     status: "Probation",
//     reportingTo: "Vikram Das",
//     skills: ["Figma", "Java", "Project Management"],
//   },
//   {
//     employeeId: "EMP-2106",
//     fullName: "Vikram Malhotra",
//     email: "vikram.malhotra@company.com",
//     department: "Design",
//     designation: "Graphic Designer",
//     salary: 2902330,
//     joiningDate: "2022-01-24",
//     workMode: "Hybrid",
//     status: "Notice Period",
//     reportingTo: "Sakshi Iyer",
//     skills: ["Figma", "SQL", "Leadership"],
//   },
//   {
//     employeeId: "EMP-2107",
//     fullName: "Neha Singh",
//     email: "neha.singh@company.com",
//     department: "Design",
//     designation: "Graphic Designer",
//     salary: 2813555,
//     joiningDate: "2021-10-29",
//     workMode: "Hybrid",
//     status: "On Leave",
//     reportingTo: "Manish Patel",
//     skills: ["Excel", "Python", "Project Management"],
//   },
//   {
//     employeeId: "EMP-2108",
//     fullName: "Karan Kulkarni",
//     email: "karan.kulkarni@company.com",
//     department: "Product",
//     designation: "Product Manager",
//     salary: 1654511,
//     joiningDate: "2022-01-29",
//     workMode: "Remote",
//     status: "Active",
//     reportingTo: "Ananya Sharma",
//     skills: ["Market Research", "Python", "Leadership"],
//   },
//   {
//     employeeId: "EMP-2109",
//     fullName: "Pooja Kulkarni",
//     email: "pooja.kulkarni@company.com",
//     department: "Design",
//     designation: "Product Designer",
//     salary: 848854,
//     joiningDate: "2021-04-06",
//     workMode: "On-site",
//     status: "Probation",
//     reportingTo: "Rishabh Malhotra",
//     skills: ["SQL", "CRM", "Python"],
//   },
//   {
//     employeeId: "EMP-2110",
//     fullName: "Siddharth Sharma",
//     email: "siddharth.sharma@company.com",
//     department: "Marketing",
//     designation: "Growth Lead",
//     salary: 1631856,
//     joiningDate: "2024-12-02",
//     workMode: "Remote",
//     status: "On Leave",
//     reportingTo: "Palak Reddy",
//     skills: ["CRM", "Python", "Project Management"],
//   },
//   {
//     employeeId: "EMP-2111",
//     fullName: "Anjali Kulkarni",
//     email: "anjali.kulkarni@company.com",
//     department: "Design",
//     designation: "UI/UX Designer",
//     salary: 2734069,
//     joiningDate: "2021-11-15",
//     workMode: "On-site",
//     status: "Active",
//     reportingTo: "Karan Iyer",
//     skills: ["Public Speaking", "SQL", "Market Research"],
//   },
//   {
//     employeeId: "EMP-2112",
//     fullName: "Rohan Iyer",
//     email: "rohan.iyer@company.com",
//     department: "Marketing",
//     designation: "Content Writer",
//     salary: 2770306,
//     joiningDate: "2023-10-23",
//     workMode: "Hybrid",
//     status: "Active",
//     reportingTo: "Megha Reddy",
//     skills: ["Excel", "Python", "SQL"],
//   },
//   {
//     employeeId: "EMP-2113",
//     fullName: "Isha Sharma",
//     email: "isha.sharma@company.com",
//     department: "Finance",
//     designation: "Financial Analyst",
//     salary: 2009527,
//     joiningDate: "2020-12-12",
//     workMode: "On-site",
//     status: "On Leave",
//     reportingTo: "Manish Patel",
//     skills: ["CRM", "Figma", "Python"],
//   },
//   {
//     employeeId: "EMP-2114",
//     fullName: "Manish Reddy",
//     email: "manish.reddy@company.com",
//     department: "Operations",
//     designation: "Supply Chain Manager",
//     salary: 2098501,
//     joiningDate: "2022-10-14",
//     workMode: "Remote",
//     status: "Notice Period",
//     reportingTo: "Tripti Reddy",
//     skills: ["Public Speaking", "Java", "Python"],
//   },
//   {
//     employeeId: "EMP-2115",
//     fullName: "Kavita Joshi",
//     email: "kavita.joshi@company.com",
//     department: "Engineering",
//     designation: "Data Scientist",
//     salary: 2823975,
//     joiningDate: "2024-10-23",
//     workMode: "Remote",
//     status: "Notice Period",
//     reportingTo: "Deepika Iyer",
//     skills: ["Java", "Market Research", "Project Management"],
//   },
//   {
//     employeeId: "EMP-2116",
//     fullName: "Abhishek Sharma",
//     email: "abhishek.sharma@company.com",
//     department: "Operations",
//     designation: "Operations Associate",
//     salary: 2888476,
//     joiningDate: "2021-10-25",
//     workMode: "Remote",
//     status: "Probation",
//     reportingTo: "Varun Joshi",
//     skills: ["Project Management", "Python", "Market Research"],
//   },
//   {
//     employeeId: "EMP-2117",
//     fullName: "Deepika Nair",
//     email: "deepika.nair@company.com",
//     department: "Marketing",
//     designation: "Social Media Manager",
//     salary: 2182644,
//     joiningDate: "2022-05-17",
//     workMode: "Remote",
//     status: "On Leave",
//     reportingTo: "Nikhil Reddy",
//     skills: ["Python", "Market Research", "Public Speaking"],
//   },
//   {
//     employeeId: "EMP-2118",
//     fullName: "Varun Sharma",
//     email: "varun.sharma@company.com",
//     department: "Marketing",
//     designation: "Growth Lead",
//     salary: 3257244,
//     joiningDate: "2023-09-09",
//     workMode: "Hybrid",
//     status: "On Leave",
//     reportingTo: "Nikhil Malhotra",
//     skills: ["Figma", "Public Speaking", "Excel"],
//   },
//   {
//     employeeId: "EMP-2119",
//     fullName: "Tanvi Das",
//     email: "tanvi.das@company.com",
//     department: "Operations",
//     designation: "Operations Associate",
//     salary: 1906743,
//     joiningDate: "2022-10-30",
//     workMode: "Remote",
//     status: "Active",
//     reportingTo: "Navya Mehta",
//     skills: ["CRM", "Leadership", "Public Speaking"],
//   },
//   {
//     employeeId: "EMP-2120",
//     fullName: "Sahil Das",
//     email: "sahil.das@company.com",
//     department: "Design",
//     designation: "Graphic Designer",
//     salary: 2710157,
//     joiningDate: "2021-04-15",
//     workMode: "On-site",
//     status: "Notice Period",
//     reportingTo: "Manish Sharma",
//     skills: ["Excel", "CRM", "Java"],
//   },
//   {
//     employeeId: "EMP-2121",
//     fullName: "Riya Das",
//     email: "riya.das@company.com",
//     department: "Engineering",
//     designation: "Data Scientist",
//     salary: 3370175,
//     joiningDate: "2023-11-13",
//     workMode: "Hybrid",
//     status: "On Leave",
//     reportingTo: "Riya Das",
//     skills: ["Leadership", "Market Research", "Excel"],
//   },
//   {
//     employeeId: "EMP-2122",
//     fullName: "Aakash Singh",
//     email: "aakash.singh@company.com",
//     department: "Engineering",
//     designation: "Data Scientist",
//     salary: 2279363,
//     joiningDate: "2020-09-04",
//     workMode: "On-site",
//     status: "Probation",
//     reportingTo: "Vivek Chawla",
//     skills: ["Market Research", "Excel", "Java"],
//   },
//   {
//     employeeId: "EMP-2123",
//     fullName: "Simran Gupta",
//     email: "simran.gupta@company.com",
//     department: "Operations",
//     designation: "Supply Chain Manager",
//     salary: 1481222,
//     joiningDate: "2023-04-11",
//     workMode: "On-site",
//     status: "On Leave",
//     reportingTo: "Yash Das",
//     skills: ["Figma", "CRM", "Excel"],
//   },
//   {
//     employeeId: "EMP-2124",
//     fullName: "Deepak Chawla",
//     email: "deepak.chawla@company.com",
//     department: "Operations",
//     designation: "Operations Associate",
//     salary: 3441190,
//     joiningDate: "2022-06-13",
//     workMode: "Remote",
//     status: "Probation",
//     reportingTo: "Nikhil Verma",
//     skills: ["SQL", "Public Speaking", "Leadership"],
//   },
//   {
//     employeeId: "EMP-2125",
//     fullName: "Shweta Sharma",
//     email: "shweta.sharma@company.com",
//     department: "Engineering",
//     designation: "QA Tester",
//     salary: 2947994,
//     joiningDate: "2023-08-04",
//     workMode: "Remote",
//     status: "Notice Period",
//     reportingTo: "Neha Chawla",
//     skills: ["Project Management", "Leadership", "Python"],
//   },
//   {
//     employeeId: "EMP-2126",
//     fullName: "Arjun Gupta",
//     email: "arjun.gupta@company.com",
//     department: "Marketing",
//     designation: "SEO Specialist",
//     salary: 1998386,
//     joiningDate: "2024-11-07",
//     workMode: "Hybrid",
//     status: "Active",
//     reportingTo: "Deepika Joshi",
//     skills: ["Market Research", "Figma", "Project Management"],
//   },
//   {
//     employeeId: "EMP-2127",
//     fullName: "Kritika Joshi",
//     email: "kritika.joshi@company.com",
//     department: "Engineering",
//     designation: "QA Tester",
//     salary: 1605893,
//     joiningDate: "2024-05-09",
//     workMode: "On-site",
//     status: "Active",
//     reportingTo: "Vivek Sharma",
//     skills: ["Market Research", "Python", "Java"],
//   },
//   {
//     employeeId: "EMP-2128",
//     fullName: "Yash Sharma",
//     email: "yash.sharma@company.com",
//     department: "Finance",
//     designation: "Accountant",
//     salary: 831474,
//     joiningDate: "2023-05-16",
//     workMode: "Remote",
//     status: "Probation",
//     reportingTo: "Aaryan Nair",
//     skills: ["SQL", "Project Management", "Public Speaking"],
//   },
//   {
//     employeeId: "EMP-2129",
//     fullName: "Megha Verma",
//     email: "megha.verma@company.com",
//     department: "Finance",
//     designation: "Accountant",
//     salary: 2065405,
//     joiningDate: "2022-07-13",
//     workMode: "Remote",
//     status: "On Leave",
//     reportingTo: "Vanshika Nair",
//     skills: ["SQL", "Market Research", "Figma"],
//   },
//   {
//     employeeId: "EMP-2130",
//     fullName: "Prateek Chawla",
//     email: "prateek.chawla@company.com",
//     department: "Design",
//     designation: "Product Designer",
//     salary: 914918,
//     joiningDate: "2022-10-04",
//     workMode: "Remote",
//     status: "Probation",
//     reportingTo: "Abhishek Iyer",
//     skills: ["Market Research", "Excel", "SQL"],
//   },
//   {
//     employeeId: "EMP-2131",
//     fullName: "Sakshi Joshi",
//     email: "sakshi.joshi@company.com",
//     department: "Operations",
//     designation: "Supply Chain Manager",
//     salary: 820645,
//     joiningDate: "2024-10-03",
//     workMode: "Remote",
//     status: "Active",
//     reportingTo: "Rahul Malhotra",
//     skills: ["Public Speaking", "SQL", "Python"],
//   },
//   {
//     employeeId: "EMP-2132",
//     fullName: "Gaurav Verma",
//     email: "gaurav.verma@company.com",
//     department: "Marketing",
//     designation: "Content Writer",
//     salary: 3094478,
//     joiningDate: "2022-01-16",
//     workMode: "On-site",
//     status: "On Leave",
//     reportingTo: "Neha Gupta",
//     skills: ["Python", "CRM", "Java"],
//   },
//   {
//     employeeId: "EMP-2133",
//     fullName: "Ananya Gupta",
//     email: "ananya.gupta@company.com",
//     department: "Product",
//     designation: "Product Analyst",
//     salary: 1744511,
//     joiningDate: "2021-10-16",
//     workMode: "Remote",
//     status: "Notice Period",
//     reportingTo: "Kavita Patel",
//     skills: ["Python", "CRM", "Java"],
//   },
//   {
//     employeeId: "EMP-2134",
//     fullName: "Rishabh Singh",
//     email: "rishabh.singh@company.com",
//     department: "Human Resources",
//     designation: "HR Manager",
//     salary: 2962164,
//     joiningDate: "2023-09-18",
//     workMode: "Hybrid",
//     status: "Probation",
//     reportingTo: "Palak Malhotra",
//     skills: ["Java", "Leadership", "SQL"],
//   },
//   {
//     employeeId: "EMP-2135",
//     fullName: "Tripti Nair",
//     email: "tripti.nair@company.com",
//     department: "Marketing",
//     designation: "Content Writer",
//     salary: 787924,
//     joiningDate: "2020-12-02",
//     workMode: "Remote",
//     status: "Notice Period",
//     reportingTo: "Deepika Malhotra",
//     skills: ["Leadership", "Project Management", "Public Speaking"],
//   },
//   {
//     employeeId: "EMP-2136",
//     fullName: "Mayank Iyer",
//     email: "mayank.iyer@company.com",
//     department: "Engineering",
//     designation: "DevOps Engineer",
//     salary: 2964649,
//     joiningDate: "2020-09-01",
//     workMode: "Hybrid",
//     status: "Probation",
//     reportingTo: "Kavita Reddy",
//     skills: ["Public Speaking", "Market Research", "Python"],
//   },
//   {
//     employeeId: "EMP-2137",
//     fullName: "Sonal Verma",
//     email: "sonal.verma@company.com",
//     department: "Operations",
//     designation: "Logistics Coordinator",
//     salary: 2639152,
//     joiningDate: "2023-06-10",
//     workMode: "Hybrid",
//     status: "On Leave",
//     reportingTo: "Sneha Malhotra",
//     skills: ["Java", "SQL", "CRM"],
//   },
//   {
//     employeeId: "EMP-2138",
//     fullName: "Aaryan Singh",
//     email: "aaryan.singh@company.com",
//     department: "Product",
//     designation: "Associate PM",
//     salary: 851621,
//     joiningDate: "2022-07-12",
//     workMode: "On-site",
//     status: "Notice Period",
//     reportingTo: "Karan Kulkarni",
//     skills: ["Public Speaking", "SQL", "Java"],
//   },
//   {
//     employeeId: "EMP-2139",
//     fullName: "Bhavna Gupta",
//     email: "bhavna.gupta@company.com",
//     department: "Marketing",
//     designation: "Growth Lead",
//     salary: 2520223,
//     joiningDate: "2022-09-30",
//     workMode: "On-site",
//     status: "Active",
//     reportingTo: "Kavita Patel",
//     skills: ["Public Speaking", "Java", "CRM"],
//   },
//   {
//     employeeId: "EMP-2140",
//     fullName: "Dev Das",
//     email: "dev.das@company.com",
//     department: "Finance",
//     designation: "Financial Analyst",
//     salary: 3274441,
//     joiningDate: "2022-11-19",
//     workMode: "Remote",
//     status: "Probation",
//     reportingTo: "Neha Verma",
//     skills: ["Python", "SQL", "Market Research"],
//   },
//   {
//     employeeId: "EMP-2141",
//     fullName: "Ishita Chawla",
//     email: "ishita.chawla@company.com",
//     department: "Design",
//     designation: "Product Designer",
//     salary: 1413198,
//     joiningDate: "2022-07-11",
//     workMode: "On-site",
//     status: "Active",
//     reportingTo: "Vivek Joshi",
//     skills: ["Public Speaking", "CRM", "Project Management"],
//   },
//   {
//     employeeId: "EMP-2142",
//     fullName: "Harsh Verma",
//     email: "harsh.verma@company.com",
//     department: "Sales",
//     designation: "Sales Manager",
//     salary: 2563111,
//     joiningDate: "2022-10-27",
//     workMode: "Remote",
//     status: "Active",
//     reportingTo: "Bhavna Mehta",
//     skills: ["Market Research", "Excel", "Figma"],
//   },
//   {
//     employeeId: "EMP-2143",
//     fullName: "Navya Singh",
//     email: "navya.singh@company.com",
//     department: "Operations",
//     designation: "Supply Chain Manager",
//     salary: 707842,
//     joiningDate: "2023-12-27",
//     workMode: "On-site",
//     status: "Probation",
//     reportingTo: "Palak Reddy",
//     skills: ["SQL", "Leadership", "Python"],
//   },
//   {
//     employeeId: "EMP-2144",
//     fullName: "Nikhil Joshi",
//     email: "nikhil.joshi@company.com",
//     department: "Sales",
//     designation: "Sales Manager",
//     salary: 3001143,
//     joiningDate: "2024-10-16",
//     workMode: "On-site",
//     status: "Active",
//     reportingTo: "Rohan Iyer",
//     skills: ["Leadership", "Project Management", "Python"],
//   },
//   {
//     employeeId: "EMP-2145",
//     fullName: "Palak Chawla",
//     email: "palak.chawla@company.com",
//     department: "Human Resources",
//     designation: "Recruiter",
//     salary: 1592508,
//     joiningDate: "2021-07-10",
//     workMode: "Remote",
//     status: "Probation",
//     reportingTo: "Siddharth Iyer",
//     skills: ["Project Management", "Market Research", "Python"],
//   },
//   {
//     employeeId: "EMP-2146",
//     fullName: "Piyush Verma",
//     email: "piyush.verma@company.com",
//     department: "Sales",
//     designation: "Business Development Associate",
//     salary: 721584,
//     joiningDate: "2020-10-02",
//     workMode: "Remote",
//     status: "Notice Period",
//     reportingTo: "Isha Joshi",
//     skills: ["CRM", "Python", "Java"],
//   },
//   {
//     employeeId: "EMP-2147",
//     fullName: "Rashmi Gupta",
//     email: "rashmi.gupta@company.com",
//     department: "Operations",
//     designation: "Supply Chain Manager",
//     salary: 2254770,
//     joiningDate: "2023-12-03",
//     workMode: "Hybrid",
//     status: "On Leave",
//     reportingTo: "Mayank Iyer",
//     skills: ["Market Research", "Leadership", "Python"],
//   },
//   {
//     employeeId: "EMP-2148",
//     fullName: "Sarthak Nair",
//     email: "sarthak.nair@company.com",
//     department: "Engineering",
//     designation: "Software Engineer",
//     salary: 2485604,
//     joiningDate: "2022-03-01",
//     workMode: "On-site",
//     status: "On Leave",
//     reportingTo: "Piyush Mehta",
//     skills: ["Market Research", "Project Management", "Figma"],
//   },
//   {
//     employeeId: "EMP-2149",
//     fullName: "Vanshika Das",
//     email: "vanshika.das@company.com",
//     department: "Engineering",
//     designation: "QA Tester",
//     salary: 663283,
//     joiningDate: "2022-10-29",
//     workMode: "Hybrid",
//     status: "Probation",
//     reportingTo: "Piyush Singh",
//     skills: ["Leadership", "Public Speaking", "Figma"],
//   },
//   {
//     employeeId: "EMP-2150",
//     fullName: "Vivek Mehta",
//     email: "vivek.mehta@company.com",
//     department: "Marketing",
//     designation: "Growth Lead",
//     salary: 2253305,
//     joiningDate: "2024-07-09",
//     workMode: "Hybrid",
//     status: "Notice Period",
//     reportingTo: "Megha Verma",
//     skills: ["Python", "CRM", "Market Research"],
//   },
// ];

// let workmodeSal = employees.reduce((acc, emp) => {
//   acc[emp.workMode] = acc[emp.workMode]
//     ? [...acc[emp.workMode], { salary: emp.salary, name: emp.fullName }]
//     : [{ salary: emp.salary, name: emp.fullName }];
//   return acc;
// }, {});

// const data = Object.entries(workmodeSal);

// const val = data.map(([key, value]) => [
//   key,
//   value
//     .sort((a, b) => b.salary - a.salary)
//     .slice(0, 5)
//     .map((item) => item.name),
// ]);

// const ans = Object.fromEntries(val);

// console.log(ans);

//---------------------------------------------------------------------------

const employees = [
  {
    employeeId: "EMP-2101",
    fullName: "Aditi Malhotra",
    email: "aditi.malhotra@company.com",
    department: "Engineering",
    designation: "Data Scientist",
    salary: 2954628,
    joiningDate: "2021-01-09",
    workMode: "On-site",
    status: "Notice Period",
    reportingTo: "Bhavna Malhotra",
    skills: ["Market Research", "Figma", "SQL"],
  },
  {
    employeeId: "EMP-2102",
    fullName: "Rahul Reddy",
    email: "rahul.reddy@company.com",
    department: "Marketing",
    designation: "Growth Lead",
    salary: 1006504,
    joiningDate: "2021-10-24",
    workMode: "Hybrid",
    status: "Probation",
    reportingTo: "Tanvi Mehta",
    skills: ["Java", "Public Speaking", "Leadership"],
  },
  {
    employeeId: "EMP-2103",
    fullName: "Priya Mehta",
    email: "priya.mehta@company.com",
    department: "Design",
    designation: "Graphic Designer",
    salary: 1501450,
    joiningDate: "2020-05-12",
    workMode: "Remote",
    status: "On Leave",
    reportingTo: "Kavita Joshi",
    skills: ["CRM", "Excel", "Java"],
  },
  {
    employeeId: "EMP-2104",
    fullName: "Amit Patel",
    email: "amit.patel@company.com",
    department: "Engineering",
    designation: "DevOps Engineer",
    salary: 3383709,
    joiningDate: "2020-07-04",
    workMode: "Hybrid",
    status: "Active",
    reportingTo: "Shweta Sharma",
    skills: ["CRM", "Java", "Python"],
  },
  {
    employeeId: "EMP-2105",
    fullName: "Sneha Patel",
    email: "sneha.patel@company.com",
    department: "Sales",
    designation: "Account Executive",
    salary: 3278492,
    joiningDate: "2022-11-11",
    workMode: "On-site",
    status: "Probation",
    reportingTo: "Vikram Das",
    skills: ["Figma", "Java", "Project Management"],
  },
  {
    employeeId: "EMP-2106",
    fullName: "Vikram Malhotra",
    email: "vikram.malhotra@company.com",
    department: "Design",
    designation: "Graphic Designer",
    salary: 2902330,
    joiningDate: "2022-01-24",
    workMode: "Hybrid",
    status: "Notice Period",
    reportingTo: "Sakshi Iyer",
    skills: ["Figma", "SQL", "Leadership"],
  },
  {
    employeeId: "EMP-2107",
    fullName: "Neha Singh",
    email: "neha.singh@company.com",
    department: "Design",
    designation: "Graphic Designer",
    salary: 2813555,
    joiningDate: "2021-10-29",
    workMode: "Hybrid",
    status: "On Leave",
    reportingTo: "Manish Patel",
    skills: ["Excel", "Python", "Project Management"],
  },
  {
    employeeId: "EMP-2108",
    fullName: "Karan Kulkarni",
    email: "karan.kulkarni@company.com",
    department: "Product",
    designation: "Product Manager",
    salary: 1654511,
    joiningDate: "2022-01-29",
    workMode: "Remote",
    status: "Active",
    reportingTo: "Ananya Sharma",
    skills: ["Market Research", "Python", "Leadership"],
  },
  {
    employeeId: "EMP-2109",
    fullName: "Pooja Kulkarni",
    email: "pooja.kulkarni@company.com",
    department: "Design",
    designation: "Product Designer",
    salary: 848854,
    joiningDate: "2021-04-06",
    workMode: "On-site",
    status: "Probation",
    reportingTo: "Rishabh Malhotra",
    skills: ["SQL", "CRM", "Python"],
  },
  {
    employeeId: "EMP-2110",
    fullName: "Siddharth Sharma",
    email: "siddharth.sharma@company.com",
    department: "Marketing",
    designation: "Growth Lead",
    salary: 1631856,
    joiningDate: "2024-12-02",
    workMode: "Remote",
    status: "On Leave",
    reportingTo: "Palak Reddy",
    skills: ["CRM", "Python", "Project Management"],
  },
  {
    employeeId: "EMP-2111",
    fullName: "Anjali Kulkarni",
    email: "anjali.kulkarni@company.com",
    department: "Design",
    designation: "UI/UX Designer",
    salary: 2734069,
    joiningDate: "2021-11-15",
    workMode: "On-site",
    status: "Active",
    reportingTo: "Karan Iyer",
    skills: ["Public Speaking", "SQL", "Market Research"],
  },
  {
    employeeId: "EMP-2112",
    fullName: "Rohan Iyer",
    email: "rohan.iyer@company.com",
    department: "Marketing",
    designation: "Content Writer",
    salary: 2770306,
    joiningDate: "2023-10-23",
    workMode: "Hybrid",
    status: "Active",
    reportingTo: "Megha Reddy",
    skills: ["Excel", "Python", "SQL"],
  },
  {
    employeeId: "EMP-2113",
    fullName: "Isha Sharma",
    email: "isha.sharma@company.com",
    department: "Finance",
    designation: "Financial Analyst",
    salary: 2009527,
    joiningDate: "2020-12-12",
    workMode: "On-site",
    status: "On Leave",
    reportingTo: "Manish Patel",
    skills: ["CRM", "Figma", "Python"],
  },
  {
    employeeId: "EMP-2114",
    fullName: "Manish Reddy",
    email: "manish.reddy@company.com",
    department: "Operations",
    designation: "Supply Chain Manager",
    salary: 2098501,
    joiningDate: "2022-10-14",
    workMode: "Remote",
    status: "Notice Period",
    reportingTo: "Tripti Reddy",
    skills: ["Public Speaking", "Java", "Python"],
  },
  {
    employeeId: "EMP-2115",
    fullName: "Kavita Joshi",
    email: "kavita.joshi@company.com",
    department: "Engineering",
    designation: "Data Scientist",
    salary: 2823975,
    joiningDate: "2024-10-23",
    workMode: "Remote",
    status: "Notice Period",
    reportingTo: "Deepika Iyer",
    skills: ["Java", "Market Research", "Project Management"],
  },
  {
    employeeId: "EMP-2116",
    fullName: "Abhishek Sharma",
    email: "abhishek.sharma@company.com",
    department: "Operations",
    designation: "Operations Associate",
    salary: 2888476,
    joiningDate: "2021-10-25",
    workMode: "Remote",
    status: "Probation",
    reportingTo: "Varun Joshi",
    skills: ["Project Management", "Python", "Market Research"],
  },
  {
    employeeId: "EMP-2117",
    fullName: "Deepika Nair",
    email: "deepika.nair@company.com",
    department: "Marketing",
    designation: "Social Media Manager",
    salary: 2182644,
    joiningDate: "2022-05-17",
    workMode: "Remote",
    status: "On Leave",
    reportingTo: "Nikhil Reddy",
    skills: ["Python", "Market Research", "Public Speaking"],
  },
  {
    employeeId: "EMP-2118",
    fullName: "Varun Sharma",
    email: "varun.sharma@company.com",
    department: "Marketing",
    designation: "Growth Lead",
    salary: 3257244,
    joiningDate: "2023-09-09",
    workMode: "Hybrid",
    status: "On Leave",
    reportingTo: "Nikhil Malhotra",
    skills: ["Figma", "Public Speaking", "Excel"],
  },
  {
    employeeId: "EMP-2119",
    fullName: "Tanvi Das",
    email: "tanvi.das@company.com",
    department: "Operations",
    designation: "Operations Associate",
    salary: 1906743,
    joiningDate: "2022-10-30",
    workMode: "Remote",
    status: "Active",
    reportingTo: "Navya Mehta",
    skills: ["CRM", "Leadership", "Public Speaking"],
  },
  {
    employeeId: "EMP-2120",
    fullName: "Sahil Das",
    email: "sahil.das@company.com",
    department: "Design",
    designation: "Graphic Designer",
    salary: 2710157,
    joiningDate: "2021-04-15",
    workMode: "On-site",
    status: "Notice Period",
    reportingTo: "Manish Sharma",
    skills: ["Excel", "CRM", "Java"],
  },
  {
    employeeId: "EMP-2121",
    fullName: "Riya Das",
    email: "riya.das@company.com",
    department: "Engineering",
    designation: "Data Scientist",
    salary: 3370175,
    joiningDate: "2023-11-13",
    workMode: "Hybrid",
    status: "On Leave",
    reportingTo: "Riya Das",
    skills: ["Leadership", "Market Research", "Excel"],
  },
  {
    employeeId: "EMP-2122",
    fullName: "Aakash Singh",
    email: "aakash.singh@company.com",
    department: "Engineering",
    designation: "Data Scientist",
    salary: 2279363,
    joiningDate: "2020-09-04",
    workMode: "On-site",
    status: "Probation",
    reportingTo: "Vivek Chawla",
    skills: ["Market Research", "Excel", "Java"],
  },
  {
    employeeId: "EMP-2123",
    fullName: "Simran Gupta",
    email: "simran.gupta@company.com",
    department: "Operations",
    designation: "Supply Chain Manager",
    salary: 1481222,
    joiningDate: "2023-04-11",
    workMode: "On-site",
    status: "On Leave",
    reportingTo: "Yash Das",
    skills: ["Figma", "CRM", "Excel"],
  },
  {
    employeeId: "EMP-2124",
    fullName: "Deepak Chawla",
    email: "deepak.chawla@company.com",
    department: "Operations",
    designation: "Operations Associate",
    salary: 3441190,
    joiningDate: "2022-06-13",
    workMode: "Remote",
    status: "Probation",
    reportingTo: "Nikhil Verma",
    skills: ["SQL", "Public Speaking", "Leadership"],
  },
  {
    employeeId: "EMP-2125",
    fullName: "Shweta Sharma",
    email: "shweta.sharma@company.com",
    department: "Engineering",
    designation: "QA Tester",
    salary: 2947994,
    joiningDate: "2023-08-04",
    workMode: "Remote",
    status: "Notice Period",
    reportingTo: "Neha Chawla",
    skills: ["Project Management", "Leadership", "Python"],
  },
  {
    employeeId: "EMP-2126",
    fullName: "Arjun Gupta",
    email: "arjun.gupta@company.com",
    department: "Marketing",
    designation: "SEO Specialist",
    salary: 1998386,
    joiningDate: "2024-11-07",
    workMode: "Hybrid",
    status: "Active",
    reportingTo: "Deepika Joshi",
    skills: ["Market Research", "Figma", "Project Management"],
  },
  {
    employeeId: "EMP-2127",
    fullName: "Kritika Joshi",
    email: "kritika.joshi@company.com",
    department: "Engineering",
    designation: "QA Tester",
    salary: 1605893,
    joiningDate: "2024-05-09",
    workMode: "On-site",
    status: "Active",
    reportingTo: "Vivek Sharma",
    skills: ["Market Research", "Python", "Java"],
  },
  {
    employeeId: "EMP-2128",
    fullName: "Yash Sharma",
    email: "yash.sharma@company.com",
    department: "Finance",
    designation: "Accountant",
    salary: 831474,
    joiningDate: "2023-05-16",
    workMode: "Remote",
    status: "Probation",
    reportingTo: "Aaryan Nair",
    skills: ["SQL", "Project Management", "Public Speaking"],
  },
  {
    employeeId: "EMP-2129",
    fullName: "Megha Verma",
    email: "megha.verma@company.com",
    department: "Finance",
    designation: "Accountant",
    salary: 2065405,
    joiningDate: "2022-07-13",
    workMode: "Remote",
    status: "On Leave",
    reportingTo: "Vanshika Nair",
    skills: ["SQL", "Market Research", "Figma"],
  },
  {
    employeeId: "EMP-2130",
    fullName: "Prateek Chawla",
    email: "prateek.chawla@company.com",
    department: "Design",
    designation: "Product Designer",
    salary: 914918,
    joiningDate: "2022-10-04",
    workMode: "Remote",
    status: "Probation",
    reportingTo: "Abhishek Iyer",
    skills: ["Market Research", "Excel", "SQL"],
  },
  {
    employeeId: "EMP-2131",
    fullName: "Sakshi Joshi",
    email: "sakshi.joshi@company.com",
    department: "Operations",
    designation: "Supply Chain Manager",
    salary: 820645,
    joiningDate: "2024-10-03",
    workMode: "Remote",
    status: "Active",
    reportingTo: "Rahul Malhotra",
    skills: ["Public Speaking", "SQL", "Python"],
  },
  {
    employeeId: "EMP-2132",
    fullName: "Gaurav Verma",
    email: "gaurav.verma@company.com",
    department: "Marketing",
    designation: "Content Writer",
    salary: 3094478,
    joiningDate: "2022-01-16",
    workMode: "On-site",
    status: "On Leave",
    reportingTo: "Neha Gupta",
    skills: ["Python", "CRM", "Java"],
  },
  {
    employeeId: "EMP-2133",
    fullName: "Ananya Gupta",
    email: "ananya.gupta@company.com",
    department: "Product",
    designation: "Product Analyst",
    salary: 1744511,
    joiningDate: "2021-10-16",
    workMode: "Remote",
    status: "Notice Period",
    reportingTo: "Kavita Patel",
    skills: ["Python", "CRM", "Java"],
  },
  {
    employeeId: "EMP-2134",
    fullName: "Rishabh Singh",
    email: "rishabh.singh@company.com",
    department: "Human Resources",
    designation: "HR Manager",
    salary: 2962164,
    joiningDate: "2023-09-18",
    workMode: "Hybrid",
    status: "Probation",
    reportingTo: "Palak Malhotra",
    skills: ["Java", "Leadership", "SQL"],
  },
  {
    employeeId: "EMP-2135",
    fullName: "Tripti Nair",
    email: "tripti.nair@company.com",
    department: "Marketing",
    designation: "Content Writer",
    salary: 787924,
    joiningDate: "2020-12-02",
    workMode: "Remote",
    status: "Notice Period",
    reportingTo: "Deepika Malhotra",
    skills: ["Leadership", "Project Management", "Public Speaking"],
  },
  {
    employeeId: "EMP-2136",
    fullName: "Mayank Iyer",
    email: "mayank.iyer@company.com",
    department: "Engineering",
    designation: "DevOps Engineer",
    salary: 2964649,
    joiningDate: "2020-09-01",
    workMode: "Hybrid",
    status: "Probation",
    reportingTo: "Kavita Reddy",
    skills: ["Public Speaking", "Market Research", "Python"],
  },
  {
    employeeId: "EMP-2137",
    fullName: "Sonal Verma",
    email: "sonal.verma@company.com",
    department: "Operations",
    designation: "Logistics Coordinator",
    salary: 2639152,
    joiningDate: "2023-06-10",
    workMode: "Hybrid",
    status: "On Leave",
    reportingTo: "Sneha Malhotra",
    skills: ["Java", "SQL", "CRM"],
  },
  {
    employeeId: "EMP-2138",
    fullName: "Aaryan Singh",
    email: "aaryan.singh@company.com",
    department: "Product",
    designation: "Associate PM",
    salary: 851621,
    joiningDate: "2022-07-12",
    workMode: "On-site",
    status: "Notice Period",
    reportingTo: "Karan Kulkarni",
    skills: ["Public Speaking", "SQL", "Java"],
  },
  {
    employeeId: "EMP-2139",
    fullName: "Bhavna Gupta",
    email: "bhavna.gupta@company.com",
    department: "Marketing",
    designation: "Growth Lead",
    salary: 2520223,
    joiningDate: "2022-09-30",
    workMode: "On-site",
    status: "Active",
    reportingTo: "Kavita Patel",
    skills: ["Public Speaking", "Java", "CRM"],
  },
  {
    employeeId: "EMP-2140",
    fullName: "Dev Das",
    email: "dev.das@company.com",
    department: "Finance",
    designation: "Financial Analyst",
    salary: 3274441,
    joiningDate: "2022-11-19",
    workMode: "Remote",
    status: "Probation",
    reportingTo: "Neha Verma",
    skills: ["Python", "SQL", "Market Research"],
  },
  {
    employeeId: "EMP-2141",
    fullName: "Ishita Chawla",
    email: "ishita.chawla@company.com",
    department: "Design",
    designation: "Product Designer",
    salary: 1413198,
    joiningDate: "2022-07-11",
    workMode: "On-site",
    status: "Active",
    reportingTo: "Vivek Joshi",
    skills: ["Public Speaking", "CRM", "Project Management"],
  },
  {
    employeeId: "EMP-2142",
    fullName: "Harsh Verma",
    email: "harsh.verma@company.com",
    department: "Sales",
    designation: "Sales Manager",
    salary: 2563111,
    joiningDate: "2022-10-27",
    workMode: "Remote",
    status: "Active",
    reportingTo: "Bhavna Mehta",
    skills: ["Market Research", "Excel", "Figma"],
  },
  {
    employeeId: "EMP-2143",
    fullName: "Navya Singh",
    email: "navya.singh@company.com",
    department: "Operations",
    designation: "Supply Chain Manager",
    salary: 707842,
    joiningDate: "2023-12-27",
    workMode: "On-site",
    status: "Probation",
    reportingTo: "Palak Reddy",
    skills: ["SQL", "Leadership", "Python"],
  },
  {
    employeeId: "EMP-2144",
    fullName: "Nikhil Joshi",
    email: "nikhil.joshi@company.com",
    department: "Sales",
    designation: "Sales Manager",
    salary: 3001143,
    joiningDate: "2024-10-16",
    workMode: "On-site",
    status: "Active",
    reportingTo: "Rohan Iyer",
    skills: ["Leadership", "Project Management", "Python"],
  },
  {
    employeeId: "EMP-2145",
    fullName: "Palak Chawla",
    email: "palak.chawla@company.com",
    department: "Human Resources",
    designation: "Recruiter",
    salary: 1592508,
    joiningDate: "2021-07-10",
    workMode: "Remote",
    status: "Probation",
    reportingTo: "Siddharth Iyer",
    skills: ["Project Management", "Market Research", "Python"],
  },
  {
    employeeId: "EMP-2146",
    fullName: "Piyush Verma",
    email: "piyush.verma@company.com",
    department: "Sales",
    designation: "Business Development Associate",
    salary: 721584,
    joiningDate: "2020-10-02",
    workMode: "Remote",
    status: "Notice Period",
    reportingTo: "Isha Joshi",
    skills: ["CRM", "Python", "Java"],
  },
  {
    employeeId: "EMP-2147",
    fullName: "Rashmi Gupta",
    email: "rashmi.gupta@company.com",
    department: "Operations",
    designation: "Supply Chain Manager",
    salary: 2254770,
    joiningDate: "2023-12-03",
    workMode: "Hybrid",
    status: "On Leave",
    reportingTo: "Mayank Iyer",
    skills: ["Market Research", "Leadership", "Python"],
  },
  {
    employeeId: "EMP-2148",
    fullName: "Sarthak Nair",
    email: "sarthak.nair@company.com",
    department: "Engineering",
    designation: "Software Engineer",
    salary: 2485604,
    joiningDate: "2022-03-01",
    workMode: "On-site",
    status: "On Leave",
    reportingTo: "Piyush Mehta",
    skills: ["Market Research", "Project Management", "Figma"],
  },
  {
    employeeId: "EMP-2149",
    fullName: "Vanshika Das",
    email: "vanshika.das@company.com",
    department: "Engineering",
    designation: "QA Tester",
    salary: 663283,
    joiningDate: "2022-10-29",
    workMode: "Hybrid",
    status: "Probation",
    reportingTo: "Piyush Singh",
    skills: ["Leadership", "Public Speaking", "Figma"],
  },
  {
    employeeId: "EMP-2150",
    fullName: "Vivek Mehta",
    email: "vivek.mehta@company.com",
    department: "Marketing",
    designation: "Growth Lead",
    salary: 2253305,
    joiningDate: "2024-07-09",
    workMode: "Hybrid",
    status: "Notice Period",
    reportingTo: "Megha Verma",
    skills: ["Python", "CRM", "Market Research"],
  },
];

let workmodeSal = employees.reduce((acc, emp) => {
  acc[emp.workMode] = acc[emp.workMode]
    ? [...acc[emp.workMode], { salary: emp.salary, name: emp.fullName }]
    : [{ salary: emp.salary, name: emp.fullName }];
  return acc;
}, {});

const data = Object.entries(workmodeSal);

const val = data.map(([key, value]) => [
  key,
  value
    .sort((a, b) => b.salary - a.salary)
    .slice(0, 5)
    .map((item) => item.name),
]);

const ans = Object.fromEntries(val);

console.log(ans);
